collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
paths:
  static: ''
  uploads: uploads
timezone: Asia/Makassar
markdown:
  engine: kramdown
  options:
    heading_ids: false
    gfm: false
    breaks: false
    typographer: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
    treat_indentation_as_code: true
_snippets_imports:
  jekyll: true
