_schema: _schema
source: /
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_structures:
  blocks:
    style: select
    values:
      - label:
        values:
          - label: gallery
            value: 
            - id: gallery
              heading: Duis Aute Irure
              paragraph: Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos a, odio quod impedit corporis repellat facilis labore doloremque quisquam, saepe expedita quasi perferendis eum? Ipsa recusandae corrupti aliquam culpa ullam.
              gallery-images:
                - image: /images/neutral-image.jpg
                - image: /images/neutral-image.jpg
                - image: /images/neutral-image.jpg
                - image: /images/neutral-image.jpg
                - image: /images/neutral-image.jpg
                - image: /images/neutral-image.jpg
              button-text: Sign up
          - label: contact-form
            value: 
            - id: contant-form
              image: /images/neutral-image.jpg
              heading: Contact Us
              name-label: name 
              email-label: email
              message-label: message
              button-text: send
              contact-form-position: right
              
_snippets_imports:
  jekyll: true
timezone: Asia/Makassar
markdown:
  engine: kramdown
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
